name: APK Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  validation:
    name: Build & Archive release APK
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Android sdkmanager
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Build release app
        run: | 
          chmod u+x build.sh
          bash build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
         name: app
         path: build/apk/MBSample.apk
